import streamlit as st
import sqlite3
import sys
import os

# Ensure Python can find the agents and database folders
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from agents.hr_agent import chat_with_hr
from database.db_setup import init_db

# Initialize DB on startup
init_db()

st.set_page_config(page_title="Aura HR Assistant", page_icon="✨", layout="centered")

# Custom Glassmorphism CSS (Updated for Dark Text)
st.markdown("""
<style>
    .stApp, .stMarkdown, h1, h2, h3, h4, h5, h6, p { color: #1e293b !important; }
    .stApp { background: linear-gradient(135deg, #f6f8fd 0%, #f1f5f9 100%); }
    .stChatMessage {
        background: rgba(255, 255, 255, 0.4) !important;
        backdrop-filter: blur(10px);
        border: 1px solid rgba(255, 255, 255, 0.3);
        border-radius: 15px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);
        padding: 15px;
        margin-bottom: 10px;
    }
    div[data-testid="stChatInput"] {
        background: rgba(255, 255, 255, 0.6);
        backdrop-filter: blur(12px);
        border-radius: 20px;
        border: 1px solid rgba(255, 255, 255, 0.4);
    }
    div[data-testid="stChatInput"] textarea { color: #1e293b !important; }
    div[data-testid="stChatInput"] textarea::placeholder { color: #64748b !important; }
</style>
""", unsafe_allow_html=True)

st.title("✨ AI HR Assistant")
st.caption("Powered by LangChain, Tools, and Groq")

# Create Tabs
tab1, tab2 = st.tabs(["💬 HR Chat", "📊 Database Admin"])

# ==========================================
# TAB 1: THE AI CHAT INTERFACE
# ==========================================
with tab1:
    # Initialize Chat History
    if "messages" not in st.session_state:
        st.session_state.messages = []

    # Display Chat History
    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    # Chat Input
    if prompt := st.chat_input("How can I help you today?"):
        # Add user message to state
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        # Generate AI Response
        with st.chat_message("assistant"):
            with st.spinner("Processing HR Workflow..."):
                history_tuples = [(msg["role"], msg["content"]) for msg in st.session_state.messages[:-1]]
                response = chat_with_hr(prompt, chat_history=history_tuples)
                st.markdown(response)

        # Add assistant response to state
        st.session_state.messages.append({"role": "assistant", "content": response})

# ==========================================
# TAB 2: THE DATABASE DASHBOARD
# ==========================================
with tab2:
    st.subheader("Live Database Overview")
    st.write("View all records generated by the AI agent.")


    # Helper function to fetch data as a dictionary (so Streamlit knows the column names)
    def fetch_data(table_name):
        db_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'database', 'hr_database.db'))
        conn = sqlite3.connect(db_path)
        conn.row_factory = sqlite3.Row  # Returns dict-like rows for column headers
        cursor = conn.cursor()
        try:
            cursor.execute(f"SELECT * FROM {table_name}")
            rows = cursor.fetchall()
            return [dict(row) for row in rows]
        except Exception as e:
            return []
        finally:
            conn.close()


    # Create visual expanders for each table
    tables = ["employees", "leaves", "tickets", "interviews"]

    for table in tables:
        with st.expander(f"📁 {table.capitalize()} Table", expanded=True):
            data = fetch_data(table)
            if data:
                # Display as an interactive dataframe
                st.dataframe(data, use_container_width=True)
            else:
                st.info(f"No records found in the {table} table yet.")

    # Add a manual refresh button
    if st.button("🔄 Refresh Data"):
        st.rerun()